name: Build .NET and publish to NUGET

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore tools
      run: dotnet tool restore      
      working-directory: BlazorComponents

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore --verbosity normal
      
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
      working-directory: BlazorComponents

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: nugetpackage
        path: BlazorComponents/bin/Release/*.nupkg
        
  publish:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest        
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
        name: nugetpackage
        
    - name: Publish to nuget
      run:  dotnet nuget push "**/vNext.BlazorComponents.*.nupkg" -s https://api.nuget.org/v3/index.json --api-key ${{ secrets.NugetApiKey }}
